#!/data/data/com.termux/files/usr/bin/bash
# A single selection shared by login shells and desktop session launchers.
# Values in ~/.config/termux-xfce/input-method: none, nimf, fcitx5.

input_method_current() {
    local selected=none
    if [ -r "$HOME/.config/termux-xfce/input-method" ]; then
        IFS= read -r selected < "$HOME/.config/termux-xfce/input-method" || true
    fi
    case "$selected" in none|nimf|fcitx5) printf '%s\n' "$selected";; *) printf 'none\n';; esac
}

_input_method_migrate_rc() {
    local rc
    for rc in "$PREFIX/etc/bash.bashrc" "$HOME/.zshrc"; do
        [ -f "$rc" ] || continue
        # Remove only installer-owned blocks. The old locale block included a
        # command-presence test which could override an explicitly chosen IME.
        sed -i \
            -e '/^# termux-xfce-nimf$/,/^# end-termux-xfce-nimf$/d' \
            -e '/^# termux-xfce-locale$/,/^fi$/{ /^if command -v nimf /,/^fi$/d; }' \
            "$rc" || return 1
        if ! grep -qF '# termux-xfce-input-method' "$rc"; then
            cat >> "$rc" << 'RC' || return 1

# termux-xfce-input-method
[ ! -r "$PREFIX/etc/profile.d/termux-xfce-input.sh" ] || . "$PREFIX/etc/profile.d/termux-xfce-input.sh"
RC
        fi
    done
}

input_method_setup() {
    local config="$HOME/.config/termux-xfce/input-method" selected=none rc
    mkdir -p "${config%/*}" "$PREFIX/etc/profile.d" || return 1
    if [ ! -f "$config" ]; then
        # Import the previous choice once, before removing its managed RC block.
        # Fcitx takes precedence when switching left a Nimf package installed.
        for rc in "$PREFIX/etc/bash.bashrc" "$HOME/.zshrc"; do
            if command -v fcitx5 >/dev/null 2>&1 &&
               grep -Eq '^[[:space:]]*export GTK_IM_MODULE=fcitx5?$' "$rc" 2>/dev/null; then
                selected=fcitx5
                break
            elif command -v nimf >/dev/null 2>&1 &&
                 grep -Eq '^[[:space:]]*export GTK_IM_MODULE=nimf$' "$rc" 2>/dev/null; then
                selected=nimf
            fi
        done
        if [ "$selected" = none ] && command -v nimf >/dev/null 2>&1 &&
           [ -f "$HOME/.config/autostart/nimf.desktop" ] &&
           ! grep -q '^Hidden=true$' "$HOME/.config/autostart/nimf.desktop"; then
            selected=nimf
        fi
        printf '%s\n' "$selected" > "$config" || return 1
    fi
    cat > "$PREFIX/etc/profile.d/termux-xfce-input.sh" << 'ENV' || return 1
# Generated by App Installer. Selection: ~/.config/termux-xfce/input-method.
_termux_im=none
if [ -r "$HOME/.config/termux-xfce/input-method" ]; then
    IFS= read -r _termux_im < "$HOME/.config/termux-xfce/input-method" || true
fi
# KWin manages its Wayland input method; do not force X11 input modules into it.
if [ "${XDG_SESSION_TYPE:-}" = wayland ] || [ -n "${WAYLAND_DISPLAY:-}" ]; then
    unset GTK_IM_MODULE QT_IM_MODULE XMODIFIERS
else
    case "$_termux_im" in
        nimf) export GTK_IM_MODULE=nimf QT_IM_MODULE=nimf XMODIFIERS=@im=nimf ;;
        fcitx5) export GTK_IM_MODULE=fcitx QT_IM_MODULE=fcitx XMODIFIERS=@im=fcitx ;;
        *) unset GTK_IM_MODULE QT_IM_MODULE XMODIFIERS ;;
    esac
fi
unset _termux_im
ENV
    _input_method_migrate_rc || return 1
    _input_method_autostart "${1:-preserve}"
}

_input_method_autostart() {
    local selected dir="$HOME/.config/autostart" id name cmd hidden
    selected=$(input_method_current)
    mkdir -p "$dir" || return 1
    # This filename is the override for Fcitx's system autostart. Remove the
    # alternate filename used by older installers to avoid launching it twice.
    rm -f "$dir/fcitx5.desktop" || return 1
    for id in nimf org.fcitx.Fcitx5; do
        hidden=true
        case "$id" in
            nimf) name=Nimf; cmd='bash -c "pgrep -x nimf >/dev/null || exec nimf"'; [ "$selected" != nimf ] || hidden=false ;;
            *) name=Fcitx5; cmd='fcitx5 -d'; [ "$selected" != fcitx5 ] || hidden=false ;;
        esac
        # Ordinary setup keeps an autostart disabled by the user. An explicit
        # selection enables the chosen method again.
        if [ "${1:-preserve}" = preserve ] &&
           grep -q '^Hidden=true$' "$dir/$id.desktop" 2>/dev/null; then
            hidden=true
        fi
        cat > "$dir/$id.desktop" << EOF || return 1
[Desktop Entry]
Type=Application
Name=$name
Exec=$cmd
NotShowIn=KDE;
Hidden=$hidden
EOF
    done
}

input_method_select() {
    case "$1" in none|nimf|fcitx5) ;; *) return 1 ;; esac
    mkdir -p "$HOME/.config/termux-xfce" || return 1
    printf '%s\n' "$1" > "$HOME/.config/termux-xfce/input-method" || return 1
    input_method_setup select
}

input_method_remove() {
    if [ "$(input_method_current)" = "$1" ]; then
        input_method_select none
        return $?
    fi
    return 0
}
